name: Feature request
description: Suggest new features for the API
title: '[FEATURE]: '
labels: ['feature request']
body:
  - type: textarea
    id: problem-solved
    attributes:
      label: What problem is solved?
      description: |
        A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: What is the solution?
      description: |
        A clear and concise description of what you want to happen.
      placeholder: This problem is solved by doing [...]
    validations:
      required: true
  - type: textarea
    id: value-add
    attributes:
      label: What value does this add?
      description: |
        A clear description of the value this feature would add to the community and applications.
      placeholder: This would add value to the project by [...]
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: Add any other context or screenshots about the feature request here.
