---
name: Feature request
about: Suggest new features for the API
title: '[FEATURE]: '
labels: ['feature request']
---

### What problem does it solve
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### What is the solution
A clear and concise description of what you want to happen.

### Added value
A clear description of the value this feature would add to the community and applications.

### Additional notes
Add any other context or screenshots about the feature request here.